package pojos;
// Generated 2022-05-15 15:46:16 by Hibernate Tools 4.3.1



/**
 * Pracownicy generated by hbm2java
 */
public class Pracownicy  implements java.io.Serializable {


     private int pracId;
     private String pracImie;
     private String pracNazwisko;
     private int pracWiek;
     private String pracNrTelefonu;
     private String pracEmail;

    public Pracownicy() {
    }

	
    public Pracownicy(int pracId, String pracImie, String pracNazwisko, int pracWiek, String pracNrTelefonu) {
        this.pracId = pracId;
        this.pracImie = pracImie;
        this.pracNazwisko = pracNazwisko;
        this.pracWiek = pracWiek;
        this.pracNrTelefonu = pracNrTelefonu;
    }
    public Pracownicy(int pracId, String pracImie, String pracNazwisko, int pracWiek, String pracNrTelefonu, String pracEmail) {
       this.pracId = pracId;
       this.pracImie = pracImie;
       this.pracNazwisko = pracNazwisko;
       this.pracWiek = pracWiek;
       this.pracNrTelefonu = pracNrTelefonu;
       this.pracEmail = pracEmail;
    }
   
    public int getPracId() {
        return this.pracId;
    }
    
    public void setPracId(int pracId) {
        this.pracId = pracId;
    }
    public String getPracImie() {
        return this.pracImie;
    }
    
    public void setPracImie(String pracImie) {
        this.pracImie = pracImie;
    }
    public String getPracNazwisko() {
        return this.pracNazwisko;
    }
    
    public void setPracNazwisko(String pracNazwisko) {
        this.pracNazwisko = pracNazwisko;
    }
    public int getPracWiek() {
        return this.pracWiek;
    }
    
    public void setPracWiek(int pracWiek) {
        this.pracWiek = pracWiek;
    }
    public String getPracNrTelefonu() {
        return this.pracNrTelefonu;
    }
    
    public void setPracNrTelefonu(String pracNrTelefonu) {
        this.pracNrTelefonu = pracNrTelefonu;
    }
    public String getPracEmail() {
        return this.pracEmail;
    }
    
    public void setPracEmail(String pracEmail) {
        this.pracEmail = pracEmail;
    }




}


